### ISSUE TITLE
Cartesian Topology potential speedup

### ISSUE THREAD

**Issue by zamanlh** [briandconnelly/seeds#11]
In the distance calculation, we calculate the square root every time we do a comparison. Instead pre-compute radius^2, and just compare to that. This is a constant speedup, but a fairly important constant. Also, it appears that math.sqrt() is about 7% slower than just calling "from math import sqrt()", not sure if its just some overhead in importing the package. Maybe python is smart enough to unroll the above comparison properly, I'm not sure, but its something work looking into.

**Comment by briandconnelly** [comment]
There are a lot of posts out there about how to do sqrt the fastest, and it seems different people get different answers.  For me, doing the "from math import sqrt" approach is better on all machines I tested, so I'm adding that to my repository, and it'll be pushed back here soon.  Same goes for the calls to floor, ceil, and pi.

I'll mull over switching things to using radius^2.  It'd speed up the construction, but not the runs.  Not sure if that cost outweighs the (slight) increase in difficulty for someone to follow the code.

**Comment by zamanlh** [comment]
I agree with the concerns for readability, but a simple comment about how if you square both sides of the distance formula should suffice. It is hard to say how much the speedup would increase building time, since it is based on dynamic programing. It will of course have a larger effect the larger the expected neighborhood. It'll have to be based on "standard" use cases to determine if there is a significant speed up.

**Comment by briandconnelly** [comment]
Tried this out, and there was no significant distance in runtime.  Going to keep it as-is for now, but if numpy/scipy are ever added as dependencies, they have some nice distance functions that could be useful.
