### ISSUE TITLE
move runseeds.py to argparse

### ISSUE THREAD

**Issue by briandconnelly** [briandconnelly/seeds#12]
Optparse is depricated, so move to argparse.

**Comment by briandconnelly** [comment]
This requires Python 2.7 or greater, which are still kind of rare.  Hold off on this a bit.

**Comment by nahumj** [comment]
I could write a conditional import of argparse, and use it if it is available. Unfortunately, this would complicate testing.

**Comment by briandconnelly** [comment]
Yeah, that and the fact that if someone were to add additional command-line arguments, they'd have to make sure they do both implementations.

Python 2.7 seems to becoming much more common (it's included in Lion and recent Ubuntu), so maybe the time to make the switch is soon.

**Comment by briandconnelly** [comment]
I'm no longer hesitant about requiring Python 2.7. This change has been made and pushed.
