### ISSUE TITLE
Remove Snapshot stuff from base system

### ISSUE THREAD

**Issue by briandconnelly** [briandconnelly/seeds#34]
Make all of this a plugin.  Can remove code from World.

**Comment by briandconnelly** [comment]
Will also need to be removed as a command line argument from runseeds.py (unless that goes in and adds the action and calls the appropriate function, which is do-able).

**Comment by zamanlh** [comment]
It would neat to have plugins able to "register" command line args, is that possible with the new optparse stuffs?

**Comment by briandconnelly** [comment]
Waiting to switch to optparse, since it's a python 2.7 and 3.0 feature, and a lot of people are still in 2.6.

I think it'd be tricky, as well, because plugins are loaded from the directories specified in the command line or config file, so it'd have to parse the command line, load the plugins, and then parse the command line again.

Aside from special cases like writing snapshots, it seems to me that the number of situations where a new command line argument makes much more sense than using --param is pretty small.  In those cases, maybe it makes more sense to write a new program to run and manage the experiment.  My intention is for that to be pretty easy.

**Comment by briandconnelly** [comment]
Snapshots have been removed.  Will push changes shortly.
