### ISSUE TITLE
Bitstring Quasispecies Model

### ISSUE THREAD

**Issue by zamanlh** [briandconnelly/seeds#37]
I'm on it...

This is what I'm thinking. We need a high but narrow peak, and a wide but lower second peak. Maybe 10 bits, the first 3 bits are the high but narrow peak, where having only these bits turned on allow you to be on the peak. Having 1 or 2 bits would be less fit than having 3, but any of the other 9 bits on would move you to a lower fitness. The other 6 bits could be additive and require you to not have any of the first 3 bits on. The highest fitness you can have in the 6 later bits would have to be less than having all 3 first bits on.

**Comment by briandconnelly** [comment]
Awesome!  It'd be good to get one of these started.
