### ISSUE TITLE
Closing File Handles

### ISSUE THREAD

**Issue by nahumj** [briandconnelly/seeds#73]
In many of the PrintActions a file is opened for writing, but never closed. This hasn't caused problems yet because when the python interpreter ends, it automatically closes open file handles. However, this is bad form and dangerous. If the PrintActions had some method that specified they were done (inverse of init), they could close their files.

**Comment by briandconnelly** [comment]
All actions have a teardown method that can be used for this.  I agree with your point---even though python programmers typically don't do the close, which always bothered me---so I'll work to get those in the included plugins asap.
